name: platform_code_builder
description: platform code builder.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  source_gen: any
  yaml: any
  code_builder: any
  dart_style: any
  lakos: any
  chalkdart: any

dev_dependencies:
  build_runner: any
